// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze() {
  return window['go']['main']['App']['Analyze']();
}

export function CollectBookmarks() {
  return window['go']['main']['App']['CollectBookmarks']();
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function ExportBookmarks() {
  return window['go']['main']['App']['ExportBookmarks']();
}

export function FetchPageHTML(arg1) {
  return window['go']['main']['App']['FetchPageHTML'](arg1);
}

export function ForceBackupAll() {
  return window['go']['main']['App']['ForceBackupAll']();
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetBookmarkCount() {
  return window['go']['main']['App']['GetBookmarkCount']();
}

export function GetBookmarks() {
  return window['go']['main']['App']['GetBookmarks']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFolderSettings() {
  return window['go']['main']['App']['GetFolderSettings']();
}

export function GetFolderTree() {
  return window['go']['main']['App']['GetFolderTree']();
}

export function GetLastAnalysisMeta() {
  return window['go']['main']['App']['GetLastAnalysisMeta']();
}

export function GetProfileDiffDetail(arg1) {
  return window['go']['main']['App']['GetProfileDiffDetail'](arg1);
}

export function GetPromptProfiles() {
  return window['go']['main']['App']['GetPromptProfiles']();
}

export function GetSyncPreview() {
  return window['go']['main']['App']['GetSyncPreview']();
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function LoadLastAnalysis() {
  return window['go']['main']['App']['LoadLastAnalysis']();
}

export function RestoreSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1, arg2);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveCustomProfiles(arg1) {
  return window['go']['main']['App']['SaveCustomProfiles'](arg1);
}

export function SaveFolderSettings(arg1) {
  return window['go']['main']['App']['SaveFolderSettings'](arg1);
}

export function ScanProfiles() {
  return window['go']['main']['App']['ScanProfiles']();
}

export function SetActivePromptID(arg1) {
  return window['go']['main']['App']['SetActivePromptID'](arg1);
}

export function SetBookmarks(arg1) {
  return window['go']['main']['App']['SetBookmarks'](arg1);
}

export function SyncToAllProfiles() {
  return window['go']['main']['App']['SyncToAllProfiles']();
}

export function SyncToProfile(arg1) {
  return window['go']['main']['App']['SyncToProfile'](arg1);
}

export function SyncToSelectedProfiles(arg1) {
  return window['go']['main']['App']['SyncToSelectedProfiles'](arg1);
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}
