// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {main} from '../models';
import {sync} from '../models';
import {browser} from '../models';

export function Analyze():Promise<engine.CategorizeResult>;

export function CollectBookmarks():Promise<main.CollectResult>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function ExportBookmarks():Promise<string>;

export function FetchPageHTML(arg1:string):Promise<main.FetchPageResult>;

export function ForceBackupAll():Promise<Array<sync.Snapshot>>;

export function GetAIConfig():Promise<main.AIConfig>;

export function GetBookmarkCount():Promise<number>;

export function GetBookmarks():Promise<Array<browser.Bookmark>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetFolderSettings():Promise<main.FolderSettings>;

export function GetFolderTree():Promise<Array<main.ProfileTree>>;

export function GetLastAnalysisMeta():Promise<main.AnalysisCacheMeta>;

export function GetProfileDiffDetail(arg1:string):Promise<main.ProfileDiffDetail>;

export function GetPromptProfiles():Promise<Record<string, any>>;

export function GetSyncPreview():Promise<main.SyncPreviewResult>;

export function ListSnapshots():Promise<Array<sync.Snapshot>>;

export function LoadLastAnalysis():Promise<main.LoadLastAnalysisResult>;

export function RestoreSnapshot(arg1:string,arg2:number):Promise<void>;

export function SaveAIConfig(arg1:main.AIConfig):Promise<void>;

export function SaveCustomProfiles(arg1:Array<main.PromptProfile>):Promise<void>;

export function SaveFolderSettings(arg1:main.FolderSettings):Promise<void>;

export function ScanProfiles():Promise<main.ScanResult>;

export function SetActivePromptID(arg1:string):Promise<void>;

export function SetBookmarks(arg1:Array<browser.Bookmark>):Promise<void>;

export function SyncToAllProfiles():Promise<main.SyncResponse>;

export function SyncToProfile(arg1:number):Promise<main.SyncResponse>;

export function SyncToSelectedProfiles(arg1:Array<string>):Promise<main.SyncResponse>;

export function TestAIConnection(arg1:main.AIConfig):Promise<main.TestResult>;
